apiVersion: v1
kind: Service
metadata:
  name: {{ include "munichbrief.fullname" . }}
  labels:
    {{- include "munichbrief.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "munichbrief.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.webPort }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
